### PR TITLE
Update Duct keys to work within a Duct 0.11 app

### PR DESCRIPTION
**Pull request by scottlowe**
Update `module.ataraxy` to work with **Duct 0.11**.

This simply means replacing `:duct.core/handler` with `:duct.handler/root`.

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Can you remove the README changes? I'd rather keep the README providing information about the stable version.

I've also been reconsidering `:duct.module/ataraxy`, for what it's worth. With `prep-key`, it becomes less necessary, as `:duct.router/ataraxy` is now almost as concise but more explicit. e.g.

```clojure
{:duct.module/ataraxy
 {[:get "/example"] [:example]}}

;; vs

{:duct.router/ataraxy
 {:routes {[:get "/example"] [:app.handler/example]}}
```

**Comment by scottlowe** [comment]
README changes have been removed.

Whilst upgrading our app and discovering this issue, I came to a similar conclusion that `:duct.router/ataraxy` could easily replace `:duct.module/ataraxy`.

However, because we have multiple definitions for routes in different `.edn` include files using the `:duct.module/ataraxy` key; when I replace those keys with `:duct.router/ataraxy {:routes ...}` I hit a duplicate key exception.

Not surprising really - I'd imagine that you didn't necessarily envisage that we'd use Ataraxy in this way! (?), but would it be possible to fix that with a `refset` somehow? The solution wasn't immediately obvious to me, so I decided to leave the multiple `:duct.module/ataraxy` keys in place for now.

**Comment by weavejester** [comment]
> However, because we have multiple definitions for routes in different `.edn` include files using the `:duct.module/ataraxy` key; when I replace those keys with `:duct.router/ataraxy {:routes ...}` I hit a duplicate key exception.

Could you explain this in a little more detail? I'm curious about your use-case, and maybe I can suggest another solution.

**Comment by scottlowe** [comment]
> Could you explain this in a little more detail?

Our application is currently partitioned into features and the Duct config loosely reflects that e.g.

```clojure
;; file: feature/foo.edn

{ :foo.bar/baz {:qux 99}

  :duct.module/ataraxy {"/foo" {"" [:foo/index]
                                "/detail" [:foo/detail]}}
                                
  ;; ...
}
```

```clojure
;; file: feature/bar.edn

{ :bar.baz/qux {:quxx 99}

  :duct.module/ataraxy {"/bar" {"" [:bar/index]
                                "/detail" [:bar/detail]}}
                                
  ;; lots of other feature config keys here
}
```

These files are subsequently included into `config.edn`. I hope that makes sense.

Clearly, we could put all the routes into one file, but it's a bit harder to follow. So cognitive load is eased by splitting up our config files and route definitions. When prepped, our config is roughly 1700 lines long and growing. The config is large because it's a multi-tenanted app, and each customer wants or needs something slightly different.

It's useful to keep the feature routes with the feature configs, but I may just consolidate the routes. My initial goal for the upgrade commit to our app was to make the least number of changes possible, but it's really not all that bad if I consolidate the routes.

**Comment by weavejester** [comment]
Splitting up the routes into features is a good idea, and something I'd like to support. However, I believe this should still be possible in Duct 0.11.0-beta1, as long as profiles are used.

So you'd make each feature derive from the base profile:

```edn
;; src/duct_hierarchy.edn
{:foo.feature/alpha [:duct.profile/base]
 :foo.feature/beta  [:duct.profile/base]}
```

Then add them to the configuration, `#duct/include`-ing the features from new files:

```edn
;; resources/foo/config.edn
{:duct.profile/base
 {:duct.core/project-ns foo}

 :foo.feature/alpha #duct/include "foo/feature/alpha"
 :foo.feature/beta  #duct/include "foo/feature/beta"

 :duct.profile/dev   #duct/include "dev"
 :duct.profile/local #duct/include "local"
 :duct.profile/prod  {}

 :duct.module/logging {}
 :duct.module.web/api {}}
```

Then you can add the feature files in:

```edn
;; resources/foo/feature/alpha.edn
{:duct.router/ataraxy {:routes {[:get "/alpha"] [:foo.handler/alpha]}}
 :foo.handler/alpha {}}
```

```edn
;; resources/foo/feature/beta.edn
{:duct.router/ataraxy {:routes {[:get "/beta"] [:foo.handler/beta]}}
 :foo.handler/beta {}}
```

And the routes should be meta-merged together:

```clojure
user=> (dev)
:loaded
dev=> (prep)
:prepped
dev=> (pprint (:duct.router/ataraxy config))
{:routes {[:get "/alpha"] [:foo.handler/alpha],
          [:get "/beta"] [:foo.handler/beta]},
 :handlers {:ataraxy.error/unmatched-path #ig/ref :duct.handler.static/not-found,
            :ataraxy.error/unmatched-method #ig/ref :duct.handler.static/method-not-allowed,
            :ataraxy.error/missing-params #ig/ref :duct.handler.static/bad-request,
            :ataraxy.error/missing-destruct #ig/ref :duct.handler.static/bad-request,
            :ataraxy.error/failed-coercions #ig/ref :duct.handler.static/bad-request,
            :ataraxy.error/failed-spec #ig/ref :duct.handler.static/bad-request,
            :foo.handler/beta #ig/ref :foo.handler/beta,
            :foo.handler/alpha #ig/ref :foo.handler/alpha}}
nil
```

Are you using profiles in this way? If you are, is there something in your routes that might be causing issues when merged?

**Comment by scottlowe** [comment]
> Are you using profiles in this way?

Ah, that's interesting. I believed that I was doing what you've demonstrated when I got the duplicate `:duct.router/ataraxy` error. I then changed everything back to `:duct.module/ataraxy`. It's possible that one of my files was misconfigured. 

Thanks for the thoughts and clarification. I will have another go at switching over to `:duct.router/ataraxy`, which will also solve our issue in wanting to move some of our handlers into namespaces that don't adhere to the handler namespace convention of module.ataraxy.

**Comment by weavejester** [comment]
Let me know how you get on. If you do have any issues I'd like to solve them.

**Comment by scottlowe** [comment]
@weavejester I've revised my app to use `:duct.router/ataraxy` and meta-merging of routes is working well now.

I got to the bottom of the duplicate key error: it was a legitimate error because I had used `:duct.router/ataraxy` in the original code where I was setting coercers, and then much higher up in the same EDN file I replaced a `:duct.module/ataraxy` with another `:duct.router/ataraxy`.

Thanks again for your help.

**Comment by weavejester** [comment]
That's good news. Let me know if you run into any more potential issues.
